### ISSUE TITLE
Create an algorithm for displaying 'hot' posts based on time, votes, keyword popularity, and endpoint

### ISSUE THREAD

**Issue by kirinrastogi** [Branch-Bunch/Carleton-Cares#11]
:peach: only
## TODO
- Create an algorithm to give 10 posts based on the specified parameters
- Implement it at /articles/hot

**Comment by JackyChiu** [comment]
@kirinrastogi Would this be `trending`?

**Comment by kirinrastogi** [comment]
@JackyChiu sure, I'm not sure exactly what to call it, but something like that.

**Comment by JackyChiu** [comment]
@kirinrastogi Okay, just bc we have a `top` which would be only take into account for votes, but since this one takes time into account, I'd assume it's `trending`

**Comment by kirinrastogi** [comment]
@JackyChiu @VikramBombhi @Tuanhao I think we should rename `Trending` to be `Hot` to follow the 3 letter scheme similar to `Top, New`. This is also a better option to default sorting to, because its about current popularity.

**Comment by JackyChiu** [comment]
Yeah sounds good to me

**Comment by JackyChiu** [comment]
@kirinrastogi when is this feature coming out? I've been dying to use it
