### ISSUE TITLE
Schema Updates - Article & Keyword + Keyword creation 

### ISSUE THREAD

**Issue by JackyChiu** [Branch-Bunch/Carleton-Cares#58]
- Article keywords to contain this format:
```js
[
  word: 'ConUHacks BB',
  id: '123'
]
```
- Keywords to contain a sum field
- Move the logic of adding a new keyword to the same time as they are created with the article

**Comment by JackyChiu** [comment]
Include #26 in PR

**Comment by VikramBombhi** [comment]
I feel like an array of objs is best
keywords: 
[
  {
    word: 'Branch'
    id: '11t'
  },
  {
    word: 'Bunch'
    id: '1s11t'
  },
]

**Comment by JackyChiu** [comment]
@VikramBombhi Yeah I meant to put it in a object, my bad
