### ISSUE TITLE
sanitize the keywords before adding them to articles, and db

### ISSUE THREAD

**Issue by kirinrastogi** [Branch-Bunch/Carleton-Cares#9]
:peach: only
## Desc
Currently, the keywords are not sanitized properly. The next 2 numbers after a percent should be removed, and spaces should be changed to underscores.

#### Modify the sanitize function to:
- Strip all punctuation
- Convert spaces to hyphens
- Remove trailing numbers after a percent sign

**Comment by kirinrastogi** [comment]
This will help with /keywords/:word since you can't have a space in that

**Comment by JackyChiu** [comment]
@kirinrastogi PR was merged, is this good to close?

**Comment by kirinrastogi** [comment]
@JackyChiu not yet, so far it just removes everything but numbers and letters. It needs to replace spaces with hyphens as well.
